/**
 * MaestroHost - SceneService
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorErrors } from './errorErrors';

/**
 * Error information
 */
export interface ModelError {
  /**
   * Represents the code for the error.
   */
  code?: number;
  /**
   * A human readable message providing details about the error.
   */
  message?: string;
  /**
   * Container for any readable information.
   */
  errors?: Array<ErrorErrors>;
}
